export interface MemberData {
  id: string;
  memberId: string;
  name: string;
  email: string;
  phone: string;
  packageId: string;
  packageName: 'Basic' | 'Standard' | 'Premium' | 'Pro';
  sponsorId: string;
  sponsorName: string;
  referralCode: string;
  networkSize: number;
  directReferrals: number;
  walletBalance: number;
  formattedWallet: string;
  totalEarnings: number;
  formattedEarnings: string;
  kycStatus: 'Approved' | 'Pending' | 'Rejected';
  status: 'Active' | 'Inactive' | 'Suspended';
  joinedDate: string;
  city: string;
  state: string;
}

export const MEMBERS: MemberData[] = [
  {
    id: 'mem-10482',
    memberId: 'MEM-10482',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@example.com',
    phone: '+91 98201 44821',
    packageId: 'pkg-premium',
    packageName: 'Premium',
    sponsorId: 'MEM-10021',
    sponsorName: 'Sunil Verma',
    referralCode: 'RAHUL4821',
    networkSize: 126,
    directReferrals: 18,
    walletBalance: 42850,
    formattedWallet: '₹42,850',
    totalEarnings: 128450,
    formattedEarnings: '₹1,28,450',
    kycStatus: 'Approved',
    status: 'Active',
    joinedDate: '12 Jan 2024',
    city: 'Mumbai',
    state: 'Maharashtra'
  },
  {
    id: 'mem-10021',
    memberId: 'MEM-10021',
    name: 'Sunil Verma',
    email: 'sunil.v@example.com',
    phone: '+91 98112 00452',
    packageId: 'pkg-pro',
    packageName: 'Pro',
    sponsorId: 'ROOT',
    sponsorName: 'Corporate Admin',
    referralCode: 'SUNILPRO',
    networkSize: 482,
    directReferrals: 34,
    walletBalance: 86400,
    formattedWallet: '₹86,400',
    totalEarnings: 342100,
    formattedEarnings: '₹3,42,100',
    kycStatus: 'Approved',
    status: 'Active',
    joinedDate: '04 Oct 2023',
    city: 'New Delhi',
    state: 'Delhi'
  },
  {
    id: 'mem-10512',
    memberId: 'MEM-10512',
    name: 'Priya Patel',
    email: 'priya.patel@example.com',
    phone: '+91 97245 88910',
    packageId: 'pkg-standard',
    packageName: 'Standard',
    sponsorId: 'MEM-10482',
    sponsorName: 'Rahul Sharma',
    referralCode: 'PRIYA512',
    networkSize: 42,
    directReferrals: 8,
    walletBalance: 18200,
    formattedWallet: '₹18,200',
    totalEarnings: 46500,
    formattedEarnings: '₹46,500',
    kycStatus: 'Approved',
    status: 'Active',
    joinedDate: '18 Feb 2024',
    city: 'Ahmedabad',
    state: 'Gujarat'
  },
  {
    id: 'mem-10534',
    memberId: 'MEM-10534',
    name: 'Ananya Rao',
    email: 'ananya.rao@example.com',
    phone: '+91 98450 12389',
    packageId: 'pkg-premium',
    packageName: 'Premium',
    sponsorId: 'MEM-10482',
    sponsorName: 'Rahul Sharma',
    referralCode: 'ANANYA9',
    networkSize: 31,
    directReferrals: 5,
    walletBalance: 24600,
    formattedWallet: '₹24,600',
    totalEarnings: 58900,
    formattedEarnings: '₹58,900',
    kycStatus: 'Pending',
    status: 'Active',
    joinedDate: '02 Mar 2024',
    city: 'Bengaluru',
    state: 'Karnataka'
  },
  {
    id: 'mem-10589',
    memberId: 'MEM-10589',
    name: 'Vikram Malhotra',
    email: 'vikram.m@example.com',
    phone: '+91 99102 33411',
    packageId: 'pkg-basic',
    packageName: 'Basic',
    sponsorId: 'MEM-10482',
    sponsorName: 'Rahul Sharma',
    referralCode: 'VIKRAM89',
    networkSize: 14,
    directReferrals: 3,
    walletBalance: 6400,
    formattedWallet: '₹6,400',
    totalEarnings: 14200,
    formattedEarnings: '₹14,200',
    kycStatus: 'Approved',
    status: 'Active',
    joinedDate: '15 Mar 2024',
    city: 'Chandigarh',
    state: 'Punjab'
  },
  {
    id: 'mem-10610',
    memberId: 'MEM-10610',
    name: 'Sneha Gupta',
    email: 'sneha.gupta@example.com',
    phone: '+91 98300 77123',
    packageId: 'pkg-standard',
    packageName: 'Standard',
    sponsorId: 'MEM-10512',
    sponsorName: 'Priya Patel',
    referralCode: 'SNEHAG',
    networkSize: 19,
    directReferrals: 4,
    walletBalance: 12500,
    formattedWallet: '₹12,500',
    totalEarnings: 29800,
    formattedEarnings: '₹29,800',
    kycStatus: 'Approved',
    status: 'Active',
    joinedDate: '28 Mar 2024',
    city: 'Kolkata',
    state: 'West Bengal'
  },
  {
    id: 'mem-10642',
    memberId: 'MEM-10642',
    name: 'Amit Roy',
    email: 'amit.roy@example.com',
    phone: '+91 94350 99812',
    packageId: 'pkg-basic',
    packageName: 'Basic',
    sponsorId: 'MEM-10512',
    sponsorName: 'Priya Patel',
    referralCode: 'AMITROY',
    networkSize: 7,
    directReferrals: 2,
    walletBalance: 3200,
    formattedWallet: '₹3,200',
    totalEarnings: 7400,
    formattedEarnings: '₹7,400',
    kycStatus: 'Pending',
    status: 'Active',
    joinedDate: '05 Apr 2024',
    city: 'Guwahati',
    state: 'Assam'
  },
  {
    id: 'mem-10675',
    memberId: 'MEM-10675',
    name: 'Neha Joshi',
    email: 'neha.joshi@example.com',
    phone: '+91 98220 54129',
    packageId: 'pkg-pro',
    packageName: 'Pro',
    sponsorId: 'MEM-10534',
    sponsorName: 'Ananya Rao',
    referralCode: 'NEHAJ',
    networkSize: 22,
    directReferrals: 6,
    walletBalance: 31000,
    formattedWallet: '₹31,000',
    totalEarnings: 78500,
    formattedEarnings: '₹78,500',
    kycStatus: 'Approved',
    status: 'Active',
    joinedDate: '12 Apr 2024',
    city: 'Pune',
    state: 'Maharashtra'
  },
  {
    id: 'mem-10701',
    memberId: 'MEM-10701',
    name: 'Rajesh Kumar',
    email: 'rajesh.k@example.com',
    phone: '+91 97110 33871',
    packageId: 'pkg-standard',
    packageName: 'Standard',
    sponsorId: 'MEM-10482',
    sponsorName: 'Rahul Sharma',
    referralCode: 'RAJESHK',
    networkSize: 9,
    directReferrals: 2,
    walletBalance: 4800,
    formattedWallet: '₹4,800',
    totalEarnings: 11200,
    formattedEarnings: '₹11,200',
    kycStatus: 'Rejected',
    status: 'Active',
    joinedDate: '20 Apr 2024',
    city: 'Jaipur',
    state: 'Rajasthan'
  },
  {
    id: 'mem-10733',
    memberId: 'MEM-10733',
    name: 'Deepak Joshi',
    email: 'deepak.j@example.com',
    phone: '+91 98970 41200',
    packageId: 'pkg-basic',
    packageName: 'Basic',
    sponsorId: 'MEM-10589',
    sponsorName: 'Vikram Malhotra',
    referralCode: 'DEEPAKJ',
    networkSize: 4,
    directReferrals: 1,
    walletBalance: 1500,
    formattedWallet: '₹1,500',
    totalEarnings: 3200,
    formattedEarnings: '₹3,200',
    kycStatus: 'Approved',
    status: 'Active',
    joinedDate: '01 May 2024',
    city: 'Dehradun',
    state: 'Uttarakhand'
  },
  {
    id: 'mem-10788',
    memberId: 'MEM-10788',
    name: 'Karthik Nair',
    email: 'karthik.nair@example.com',
    phone: '+91 98470 66219',
    packageId: 'pkg-premium',
    packageName: 'Premium',
    sponsorId: 'MEM-10610',
    sponsorName: 'Sneha Gupta',
    referralCode: 'KNAIR',
    networkSize: 8,
    directReferrals: 2,
    walletBalance: 14200,
    formattedWallet: '₹14,200',
    totalEarnings: 31000,
    formattedEarnings: '₹31,000',
    kycStatus: 'Pending',
    status: 'Active',
    joinedDate: '10 May 2024',
    city: 'Kochi',
    state: 'Kerala'
  },
  {
    id: 'mem-10815',
    memberId: 'MEM-10815',
    name: 'Kavita Deshmukh',
    email: 'kavita.d@example.com',
    phone: '+91 98600 33819',
    packageId: 'pkg-standard',
    packageName: 'Standard',
    sponsorId: 'MEM-10675',
    sponsorName: 'Neha Joshi',
    referralCode: 'KAVITAD',
    networkSize: 6,
    directReferrals: 2,
    walletBalance: 7600,
    formattedWallet: '₹7,600',
    totalEarnings: 15800,
    formattedEarnings: '₹15,800',
    kycStatus: 'Approved',
    status: 'Active',
    joinedDate: '18 May 2024',
    city: 'Nagpur',
    state: 'Maharashtra'
  },
  {
    id: 'mem-10850',
    memberId: 'MEM-10850',
    name: 'Rohan Kapoor',
    email: 'rohan.k@example.com',
    phone: '+91 98101 22904',
    packageId: 'pkg-pro',
    packageName: 'Pro',
    sponsorId: 'MEM-10482',
    sponsorName: 'Rahul Sharma',
    referralCode: 'ROHANK',
    networkSize: 12,
    directReferrals: 3,
    walletBalance: 22400,
    formattedWallet: '₹22,400',
    totalEarnings: 52000,
    formattedEarnings: '₹52,000',
    kycStatus: 'Approved',
    status: 'Active',
    joinedDate: '25 May 2024',
    city: 'Lucknow',
    state: 'Uttar Pradesh'
  }
];

export const CURRENT_LOGGED_IN_MEMBER = MEMBERS[0]; // Rahul Sharma
